### PR TITLE
Fixing failing tests

### LINKED ISSUE #58: [BUG] Failing CI
### What is the bug?
The CI has started failing: https://github.com/opensearch-project/opensearch-rs/runs/6942342645?check_suite_focus=true

With the new `cargo2junit`, the tests have started failing after errors:

```
Some errors have detailed explanations: E0277, E0283, E0425, E0432, E0599.
For more information about an error, try `rustc --explain E0277`.
warning: `yaml_test_runner` (test "mod") generated 2 warnings
error: could not compile `yaml_test_runner` due to 460 previous errors; 2 warnings emitted
[cargo-make] INFO - Running Task: install-cargo2junit
+ cd /usr/src/opensearch-rs
+ cargo install cargo2junit
    Updating crates.io index
     Ignored package `cargo2junit v0.1.12` is already installed, use --force to override
[cargo-make] INFO - Running Task: convert-test-results-junit
+ cd /usr/src/opensearch-rs
+ cat test_results/results.json
+ cargo2junit
Error: Custom { kind: NotFound, error: "No test suite results were found." }
[cargo-make] ERROR - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.
```

The tests have been silently facing these errors even before but the overall tests passed ([successful run](https://github.com/opensearch-project/opensearch-rs/runs/6762673118?check_suite_focus=true)):

```
Some errors have detailed explanations: E0277, E0283, E0425, E0432, E0599.
For more information about an error, try `rustc --explain E0277`.
warning: `yaml_test_runner` (test "mod") generated 2 warnings
error: could not compile `yaml_test_runner` due to 460 previous errors; 2 warnings emitted
[cargo-make] INFO - Running Task: install-cargo2junit
+ cd /usr/src/opensearch-rs
+ cargo install cargo2junit
    Updating crates.io index
     Ignored package `cargo2junit v0.1.10` is already installed, use --force to override
[cargo-make] INFO - Running Task: convert-test-results-junit
+ cd /usr/src/opensearch-rs
+ cat test_results/results.json
+ cargo2junit
[cargo-make] INFO - Running Task: test-yaml
```
### How can one reproduce the bug?
Run the integration tests using:

```
./.ci/run-tests opensearch 1.2.1 true
```

### What is the expected behavior?
CI should pass without errors.

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

### PR DESCRIPTION
**Pull request by VachaShah**
Signed-off-by: Vacha Shah <vachshah@amazon.com>

### Description
This is the first attempt at fixing tests failing in the CI. The issue is described in detail in #58. 

### Issues Resolved
Fixes #58 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
Still failing :(

**Comment by VachaShah** [comment]
> Still failing :(

Yeah :(. The tests with security are failing, this PR currently just fixes the ones without security. I missed to convert this to a draft.

**Comment by dblock** [comment]
Maybe we can ask @davidlago to help out?

**Comment by VachaShah** [comment]
The permissions issue is happening when calling the [delete indices api](https://github.com/opensearch-project/opensearch-rs/blob/main/yaml_test_runner/tests/common/client.rs#L211) for tests with secure OpenSearch Cluster. The tests run successfully for the OpenSearch cluster without security.

I looked through other clients and they all have the same kind of setup, call the delete indices api for cleanup but don't have this issue.

**Comment by cwperks** [comment]
Hi @VachaShah,

Deleting all indices fails because it includes the security plugin configuration indices and the security plugin prohibits that action even for admin users. By using an admin certificate, you become a "super admin" and have the ability to delete/restore all indices including the security plugin indices.

A few options to consider:

1. One straightforward solution is to add the following lines in `.ci/opensearch/Dockerfile`:

(Run this if SECURE_INTEGRATION is true)
```
RUN chmod +x $opensearch_path/plugins/opensearch-security/tools/install_demo_configuration.sh
RUN yes | $opensearch_path/plugins/opensearch-security/tools/install_demo_configuration.sh
RUN echo "plugins.security.filter_securityindex_from_all_requests: true" >> $opensearch_yml
```

The first 2 commands are necessary to perform the demo configuration because the `install_demo_configuration.sh` script is skipped if there are any `plugins.security.*` in the `opensearch.yml` file. This file is normally executed as part of the entrypoint to the Opensearch docker container.

2. The next option is to use an admin certificate to connect to the cluster as you suggested.

3. The other option to consider to to start/stop the cluster in between tests to get a pristine cluster at the beginning of every test.

The tests are currently running locally and get past the reported error with admin not having permissions. I will push a branch and try with CI as well.

**Comment by VachaShah** [comment]
> Hi @VachaShah,
> 
> Deleting all indices fails because it includes the security plugin configuration indices and the security plugin prohibits that action even for admin users (The error message is not great for this). By using an admin certificate, you become a "super admin" and have the ability to delete/restore all indices including the security plugin indices.
> 
> A few options to consider:
> 
> 1. One straightforward solution is to add the following lines in `.ci/opensearch/Dockerfile`:
> 
> (Run this if SECURE_INTEGRATION is true)
> 
> ```
> RUN chmod +x $opensearch_path/plugins/opensearch-security/tools/install_demo_configuration.sh
> RUN yes | $opensearch_path/plugins/opensearch-security/tools/install_demo_configuration.sh
> RUN echo "plugins.security.filter_securityindex_from_all_requests: true" >> $opensearch_yml
> ```
> 
> The first 2 commands are necessary to perform the demo configuration because the `install_demo_configuration.sh` script is skipped if there are any `plugins.security.*` in the `opensearch.yml` file. This `install_demo_configuration.sh` file is normally executed as part of the entrypoint to the Opensearch docker container.
> 
> 2. The next option is to use an admin certificate to connect to the cluster as you suggested.
> 3. The other option to consider to to start/stop the cluster in between tests to get a pristine cluster at the beginning of every test.
> 
> The tests are currently running locally and get past the reported error with admin not having permissions. I will push a branch and try with CI as well.

Awesome! Thank you @cwperks, the first option works perfectly to fix this issue. There are quite a few failing tests after that but it goes past the security permissions error which is great!

**Comment by saratvemulapalli** [comment]
Thanks @cwperks for the explanation. We did guess using certificates is going to provide super admin permissions and solve the problem. 
The error reason `"reason\":\"no permissions for []` is not self explanatory, could we do verbose logging ?(I can open up an issue in security if we are on the same page).
@VachaShah why was this not a problem for rest of the clients? Aren't they deleting the internal security plugin indices?

**Comment by VachaShah** [comment]
> Thanks @cwperks for the explanation. We did guess using certificates is going to provide super admin permissions and solve the problem. The error reason `"reason\":\"no permissions for []` is not self explanatory, could we do verbose logging ?(I can open up an issue in security if we are on the same page). @VachaShah why was this not a problem for rest of the clients? Aren't they deleting the internal security plugin indices?

I still don't know why the other clients don't face this issue that have the same setup (for example: https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/helpers/test.py#L83).

Another part here is that the tests are still failing after the first option (@cwperks suggested to try the admin certificate to resolve that) but the test cases used in the Rust client are very extensive and heavy since they use the test cases from [yaml tests](https://github.com/opensearch-project/OpenSearch/tree/main/rest-api-spec/src/main/resources/rest-api-spec/test) from OpenSearch. I feel we could also decouple this and write required test cases for the client since all tests from OpenSearch might not be relevant. WDYT @saratvemulapalli @dblock?

**Comment by cwperks** [comment]
Hey @VachaShah I could be wrong, but this issue is probably also affecting the python client. There is only 1 test run when security is set to True for the python client and it doesn't extend `OpenSearchTestCase` that you linked to. See the screenshots below.

When security is set to false:

Screen Shot 2022-07-21 at 9 55 05 AM

When security is set to true:

Screen Shot 2022-07-21 at 9 54 30 AM

**Comment by VachaShah** [comment]
> Hey @VachaShah I could be wrong, but this issue is probably also affecting the python client. There is only 1 test run when security is set to True for the python client and it doesn't extend `OpenSearchTestCase` that you linked to. See the screenshots below.
> 
> When security is set to false:
> 
> Screen Shot 2022-07-21 at 9 55 05 AM
> 
> When security is set to true:
> 
> Screen Shot 2022-07-21 at 9 54 30 AM

Ah!! So thats why the python client is unaffected since it is not trying to delete the security indices for the tests. Thank you so much for this finding @cwperks!

**Comment by VachaShah** [comment]
After adding the admin certificate to the tests for security (latest changes in this PR), some tests from the yaml test suite still fail with assertion errors like

```
{ "type": "test", "name": "free::search_aggregation::_220_filters_bucket::anonymous_filters_test", "event": "failed", "stdout": "thread 'main' panicked at 'assertion failed: `(left == right)`\n  left: `Number(5)`,\n right: `4`: expected value json[\"hits\"][\"total\"] to match 4 but was Number(5)', yaml_test_runner/tests/free/search_aggregation/_220_filters_bucket.rs:203:5\n" }
```

**Comment by dblock** [comment]
@VachaShah is this a small amount that gets different search results? Maybe we can mark them ignore and open an issue?

**Comment by VachaShah** [comment]
> @VachaShah is this a small amount that gets different search results? Maybe we can mark them ignore and open an issue?

Yeah its a small percentage of the whole test suite. I will create an issue for the same so that we can unblock the PRs to this repo.

**Comment by VachaShah** [comment]
@dblock I have updated the PR with the changes and the CI is green now.

**Comment by VachaShah** [comment]
Also, many thanks to @cwperks for helping with the security exception issue, the code in this PR for adding admin certificate is entirely due to his effort 🙇🏼‍♀️

**Review by Xtansia — APPROVED** [review]

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
@VachaShah What is the fall out from this change (tests removed?), open an issue for followup items?

**Comment by VachaShah** [comment]
> @VachaShah What is the fall out from this change (tests removed?), open an issue for followup items?

Created issue #66 for the fall out.

**Comment by jayaddison** [comment]
> Hey @VachaShah I could be wrong, but this issue is probably also affecting the python client. There is only 1 test run when security is set to True for the python client and it doesn't extend `OpenSearchTestCase` that you linked to. See the screenshots below.

Hi @cwperks @VachaShah @dblock - I've landed here after scouring some of the bugtracker to check on the status of https://github.com/opensearch-project/opensearch-clients/issues/58 (sidenote / bonus: a few items there are now complete, and can be checked-off).

As a consumer of the Python client library I think I'd be marginally more comfortable with the test coverage if the same tests ran in both HTTP and HTTPS modes.  Given that the test suite runs twice, once for each, the coverage and behaviour should be fine, but I'm wondering if I could offer (and whether you would accept) any contribution time to get rid of that branch condition, likely by using a similar client-certificate approach to here.

**Comment by jayaddison** [comment]
Oops, I forgot to mention (partly for my own potential future reference): I think that the key place where the tests branch in the Python client test suite is [this section of code](https://github.com/opensearch-project/opensearch-py/blob/103bc8948616dce57719ad089584e8e706427434/test_opensearchpy/run_tests.py#L135-L151).

**Pull request merged**
