### PR TITLE
Adding new OpenSearch versions and updating compatibility matrix

### PR DESCRIPTION
**Pull request by VachaShah**
Signed-off-by: Vacha Shah <vachshah@amazon.com>

### Description
Adding new OpenSearch versions and updating the compatibility matrix.

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by Xtansia — APPROVED** [review]

**Review by saratvemulapalli — APPROVED** [review]

**Comment by VachaShah** [comment]
Checking why the tests are failing.

**Comment by VachaShah** [comment]
For the failing tests, the error is:

```
error[E0432]: unresolved imports `opensearch::ilm`, `opensearch::security`, `opensearch::transform`, `opensearch::watcher`
  --> yaml_test_runner/tests/common/client.rs:42:5
   |
42 |     ilm::IlmRemovePolicyParts,
   |     ^^^ could not find `ilm` in `opensearch`
...
48 |     security::{
   |     ^^^^^^^^ could not find `security` in `opensearch`
...
55 |     transform::{
   |     ^^^^^^^^^ could not find `transform` in `opensearch`
...
58 |     watcher::WatcherDeleteWatchParts,
   |     ^^^^^^^ could not find `watcher` in `opensearch`
```

among others. Looking into why the imported files are not present in [`opensearch`](https://github.com/opensearch-project/opensearch-rs/tree/main/opensearch/src) folder.

**Comment by VachaShah** [comment]
Created issue #58 for failing CI.

**Comment by VachaShah** [comment]
Closing this PR since it is done in #59

**Pull request closed without merging**
