### PR TITLE
Bump `aws-*` dependencies from `>= 0.10` to `>= 0.53`

### LINKED ISSUE #106: [FEATURE] Does not build with newest aws rust sdk (aws-types = "0.53")
aws-types = "0.53"

error[E0432]: unresolved imports `aws_types::credentials`, `aws_types::Credentials`
  --> /home/michal/.cargo/registry/src/github.com-1ecc6299db9ec823/opensearch-2.0.0/src/http/aws_auth.rs:19:5
   |
19 |     credentials::{ProvideCredentials, SharedCredentialsProvider},
   |     ^^^^^^^^^^^ could not find `credentials` in `aws_types`
20 |     region::Region,
21 |     Credentials,
   |     ^^^^^^^^^^^ no `Credentials` in the root
   |
help: consider importing this enum instead
   |
21 |     crate::auth::Credentials;
   |

error[E0433]: failed to resolve: could not find `credentials` in `aws_types`
  --> /home/michal/.cargo/registry/src/github.com-1ecc6299db9ec823/opensearch-2.0.0/src/auth.rs:55:20
   |
55 |         aws_types::credentials::SharedCredentialsProvider,
   |                    ^^^^^^^^^^^ could not find `credentials` in `aws_types`

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `opensearch` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...

### PR DESCRIPTION
**Pull request by Xtansia**
### Description
Bump `aws-*` dependencies from `>= 0.10` to `>= 0.53`
Credential types were split from `aws-types` into `aws-credential-types`

### Issues Resolved
Resolves #106 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
So is this a breaking change?

**Comment by Xtansia** [comment]
> So is this a breaking change?

Yeah unfortunately, as due to the nature of the api it pushes that higher dependency onto the consumer (if they're using awssigv4). But we could maybe handwave it into a minor bump due to aws-* being treated as unstable and it being unrealistic to major bump the client everytime they change something. 

However I am going to think a bit about how this is exposed to clients (and my comments on #96) to see if we could nicely wall it off further.

**Comment by dblock** [comment]
Handwave it.

**Review by dblock — APPROVED** [review]

**Review by VachaShah — APPROVED** [review]

**Comment by VachaShah** [comment]
@Xtansia I could not find sample code for SigV4 in the user guide. Am I missing something or does it have to be added?

**Comment by dblock** [comment]
I have docs as part of #96, but we have more problems.

**Comment by dblock** [comment]
@Xtansia with this upgrade I am getting the following:

```
---- src/lib.rs - (line 342) stdout ----
error[E0277]: the trait bound `opensearch::auth::Credentials: From<SdkConfig>` is not satisfied
  --> src/lib.rs:359:61
   |
19 | let transport = TransportBuilder::new(conn_pool).auth(creds.try_into()?).build()?;
   |                                                             ^^^^^^^^ the trait `From<SdkConfig>` is not implemented for `opensearch::auth::Credentials`
   |
   = help: the trait `From<ClientCertificate>` is implemented for `opensearch::auth::Credentials`
   = note: required for `SdkConfig` to implement `Into<opensearch::auth::Credentials>`
   = note: required for `opensearch::auth::Credentials` to implement `TryFrom<SdkConfig>`
   = note: required for `SdkConfig` to implement `TryInto<opensearch::auth::Credentials>`
```

**Comment by Xtansia** [comment]
> @Xtansia with this upgrade I am getting the following:
> 
> ```
> ---- src/lib.rs - (line 342) stdout ----
> error[E0277]: the trait bound `opensearch::auth::Credentials: From<SdkConfig>` is not satisfied
>   --> src/lib.rs:359:61
>    |
> 19 | let transport = TransportBuilder::new(conn_pool).auth(creds.try_into()?).build()?;
>    |                                                             ^^^^^^^^ the trait `From<SdkConfig>` is not implemented for `opensearch::auth::Credentials`
>    |
>    = help: the trait `From<ClientCertificate>` is implemented for `opensearch::auth::Credentials`
>    = note: required for `SdkConfig` to implement `Into<opensearch::auth::Credentials>`
>    = note: required for `opensearch::auth::Credentials` to implement `TryFrom<SdkConfig>`
>    = note: required for `SdkConfig` to implement `TryInto<opensearch::auth::Credentials>`
> ```

@dblock Based on the error my best guess is either not having the `aws-auth` feature enabled on the crate, or mismatched version for the `aws-config` crate, Cargo.toml should be something like:
```toml
[dependencies]
opensearch = { git = "https://github.com/opensearch-project/opensearch-rs.git", features = ["aws-auth"] }
aws-config = "0.53"
```

**Pull request merged**
