### PR TITLE
Add support for inclusive naming

### LINKED ISSUE #56: [FEATURE] Add support for inclusive naming
Add support for inclusive naming by deprecating the master nomenclature.

See meta issue https://github.com/opensearch-project/opensearch-clients/issues/16 for details.

### PR DESCRIPTION
**Pull request by Xtansia**
### Description
- Adds the new `cluster_manager_timeout` parameters, deprecating `master_timeout`. 
- Adds the new `/_cat/cluster_manager` endpoint, deprecating `/_cat/master`.
- Improves code & test generation to handle adding `#[deprecated = "reason"]` attributes.

### Issues Resolved
Resolves #56 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by harshavamsi** [comment]
@Xtansia I see the PR has additional changes around tests and versions in Cargo, do we want to move them to a separate PR or it that necessary for them to work with the new naming changes? I feel it's easier to review if we move those changes into a separate PR.

**Comment by Xtansia** [comment]
> @Xtansia I see the PR has additional changes around tests and versions in Cargo, do we want to move them to a separate PR or it that necessary for them to work with the new naming changes? I feel it's easier to review if we move those changes into a separate PR.

@harshavamsi That's fair, there is some interdependency, but I'll try to chop this into some more manageable PRs.

**Comment by harshavamsi** [comment]
@dblock @VachaShah care to review and merge?

**Comment by Xtansia** [comment]
@dblock have rebased & resolved the conflict

**Review by dblock — APPROVED** [review]

**Review by VachaShah — APPROVED** [review]

**Pull request merged**
