### PR TITLE
Update base64 requirement from ^0.13 to ^0.20

### PR DESCRIPTION
**Pull request by mohe2015**
### Description
Update base64 requirement from ^0.13 to ^0.20

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by Xtansia — APPROVED** [review]

**Review by Xtansia — CHANGES_REQUESTED** [review]
Please can you add an entry to CHANGELOG.md stating the version update

**Review by Xtansia — APPROVED** [review]

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
@Xtansia Are we concerned with the compatibility CI failing?

**Comment by Xtansia** [comment]
@dblock There seems to be a pathological failing for testing unreleased 1.x (also affecting #91), the tests succeed locally but are hitting resource limits when running in GitHub Actions. I've tried running them with no changes from main, but it consistently fails with 
Screen Shot 2023-01-04 at 11 41 52 AM

**Comment by dblock** [comment]
> @dblock There seems to be a pathological failing for testing unreleased 1.x (also affecting #91), the tests succeed locally but are hitting resource limits when running in GitHub Actions. I've tried running them with no changes from main, but it consistently fails with Screen Shot 2023-01-04 at 11 41 52 AM

Want to PR removing those and open an issue for now?

**Review by VachaShah — APPROVED** [review]

**Pull request merged**
