### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by prudhvigodithi**
### Description
Update CODEOWNERS

### Issues Resolved
https://github.com/opensearch-project/opensearch-rs/issues/123

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
Please make sure `aditjind` is invited to the the repo before adding to the `CODEOWNERS` and `MAINTAINERS.md` file.
Thank you

**Comment by Xtansia** [comment]
The [org-wide MAINTAINERS.md](https://github.com/opensearch-project/.github/blob/main/RESPONSIBILITIES.md#inactivity) states that maintainership status does not expire, but permissions may be removed for security reasons, and that moving to emeritus is a choice by the maintainer. So forcefully moving someone to emeritus seems against our own policy? This was the reason they were left in Maintainer section but removed from CODEOWNERS as it breaks the one-click approval process if they are in CODEOWNERS without permissions (#160)

**Comment by dblock** [comment]
> The [org-wide MAINTAINERS.md](https://github.com/opensearch-project/.github/blob/main/RESPONSIBILITIES.md#inactivity) states that maintainership status does not expire, but permissions may be removed for security reasons, and that moving to emeritus is a choice by the maintainer. So forcefully moving someone to emeritus seems against our own policy? This was the reason they were left in Maintainer section but removed from CODEOWNERS as it breaks the one-click approval process if they are in CODEOWNERS without permissions (#160)

Are there any reasons to remove permissions? They actually aren't able to approve PRs anymore because they don't have permissions, so does that still make them maintainer? In this case would you mind merging this PR and reaching out to them to re-add them with proper permissions?

**Comment by Xtansia** [comment]
> org-wide MAINTAINERS.md

Well according to the doc they're still considered a maintainer even if inactive and it's up to them to ask for permissions to be reinstated if they wish to participate again. They did have correct permissions previously, I am unsure who removed them, I don't have repo admin permissions to do so, let alone the org-admin permissions to check the audit log.

I'm just saying we should follow our own policies, or amend them if they don't align with reality.

**Comment by dblock** [comment]
@Xtansia ok, I'm with you. 

Permissions were removed because @aditjind used to be a member of the opensearch-project org, then was removed from the org (changed jobs), and thus lost their permissions. I'll make changes to the tool to account for this. If you want to re-add them to CODEOWNERS, please feel free.

Let's close this one.

**Pull request closed without merging**
